# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4de72e6a7ab86b65112d7b7122d1892918d36d029a363fe8048afe586482748bf4888f1aa11c44e35e46a1bd159653155d79e864632f29d773490085f7ec96

test:
  secret_key_base: 69cbfbf20ce61c39ec8159efac19fb1b31de80f1572df347cfad9d7bce181ddb2a5c3a9723196f86d5c2952fc1b86b96c3b53e7da2c94b7ebd8ad7cdca2acaac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
